#+title: Webeye
#+author: Lucas Sta Maria
#+email: lucas@priime.dev

Webeye is a small package for periodically checking for webpage changes, notifying if any such changes occur. This is currently a very early version.

** Setup

*** Installation

I have not yet uploaded this package to the Racket package server. So, to install it, you will need to clone the repository and manually install it.

*Prerequisites*:

+ raco

#+begin_src sh
$ git clone https://github.com/priime0/webeye
$ cd webeye
$ raco pkg install --auto --skip-installed
#+end_src

*** Running

#+begin_src sh
$ racket main.rkt
#+end_src

** Plans

This is currently an early-stage project. I plan to add several necessary features and improvements to the current iteration.

+ /An interface for notifications/. Currently, I've hardcoded it to work with the [[https://ntfy.sh][ntfy.sh]] API for my current use cases. I plan on abstracting this out into an interface to allow for different notification services to be used.
+ /Better logging messages/. Logged messages currently don't show time or level, which would be useful.
+ /Notifications on errors/. It would be convenient to receive notifications when errors occur. *Done!*
+ /Configuration/. Currently, I intend to write a Racket ~#lang~ and ~raco~ command for configuration.
  + /Configuration for pages/. Right now, you need to hardcode it into the ~main.rkt~ file.
  + /Configuration for delay/. Currently hardcoded at 30 seconds.
